"""Pydantic models for entity types: Character, Location, Faction, TimelineEvent"""
from datetime import date
from typing import Literal

from pydantic import BaseModel, Field


class SourceReference(BaseModel):
    """Reference to where entity information came from"""
    
    source_type: Literal["book", "wiki", "manual"] = "book"
    source_id: str  # e.g., "dungeon_crawler_carl_book1"
    chapter: str | None = None
    context: str | None = None  # relevant quote or passage


class BaseEntity(BaseModel):
    """Base model for all entity types"""
    
    entity_type: str
    entity_id: str = Field(..., pattern=r"^[a-z_]+_[a-z0-9_]+$")
    name: str
    aliases: list[str] = Field(default_factory=list)
    sources: list[SourceReference] = Field(default_factory=list)
    first_appearance: str | None = None  # chapter/section
    occurrence_count: int = 0
    last_updated: date = Field(default_factory=date.today)
    
    # Canonical description (generated by summarizer)
    canonical_description: str | None = None


class Character(BaseEntity):
    """Character entity with physical traits, personality, and abilities"""
    
    entity_type: Literal["character"] = "character"
    
    # Physical traits
    physical_traits: list[str] = Field(default_factory=list)
    
    # Personality traits
    personality_traits: list[str] = Field(default_factory=list)
    
    # Abilities/skills
    abilities: list[str] = Field(default_factory=list)
    
    # Role in story
    role: str | None = None  # protagonist, antagonist, supporting, etc.
    
    # Species/race (for fantasy)
    species: str | None = None


class Location(BaseEntity):
    """Location entity with environmental and architectural details"""
    
    entity_type: Literal["location"] = "location"
    
    # Location type
    location_type: str | None = None  # city, dungeon, forest, building, etc.
    
    # Environmental description
    environment: list[str] = Field(default_factory=list)
    
    # Architectural style
    architecture: list[str] = Field(default_factory=list)
    
    # Atmosphere/tone
    atmosphere: list[str] = Field(default_factory=list)
    
    # Parent location (for hierarchy)
    parent_location_id: str | None = None


class Faction(BaseEntity):
    """Faction/organization entity"""
    
    entity_type: Literal["faction"] = "faction"
    
    # Type of faction
    faction_type: str | None = None  # guild, government, cult, military, etc.
    
    # Goals/motivations
    goals: list[str] = Field(default_factory=list)
    
    # Notable traits
    traits: list[str] = Field(default_factory=list)
    
    # Headquarters or base location
    base_location_id: str | None = None


class TimelineEvent(BaseEntity):
    """Timeline event capturing major plot points"""
    
    entity_type: Literal["timeline_event"] = "timeline_event"
    
    # Event type
    event_type: str | None = None  # battle, discovery, death, meeting, etc.
    
    # When it happened (relative or absolute)
    temporal_marker: str | None = None
    
    # Sequence order (for ordering events)
    sequence_order: int | None = None
    
    # Participating entities
    participants: list[str] = Field(default_factory=list)  # entity_ids
    
    # Location where event occurred
    location_id: str | None = None
    
    # Consequences/impact
    consequences: list[str] = Field(default_factory=list)


# Type alias for any entity
Entity = Character | Location | Faction | TimelineEvent

# Entity type to class mapping
ENTITY_CLASSES = {
    "character": Character,
    "location": Location,
    "faction": Faction,
    "timeline_event": TimelineEvent,
}
